apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bycrto434-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bycrto434-python 
  name: bycrto434-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bycrto434-python 
