apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bycrto434-python 
  janus-idp.io/tekton: bycrto434-python
  backstage.io/kubernetes-id: bycrto434-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bycrto434-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml