apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bycrto434-python-gitops
  description: This is GitOps manifest for bycrto434-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=bycrto434-python
    backstage.io/kubernetes-id: bycrto434-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: bycrto434-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bycrto434-python
